## THESE ARE DEFAULT SETTINGS
## PLEASE COPY THIS FILE TO 'upload_settings.yaml'
## AND CHANGE THEM TO SUIT YOUR PROJECT

# Facebook upload settings
files:
    (^|/|\\)comments.json:
      # in key is required when the initial level of data
      # is not a list but an object (e.g. {} instead of [])
      in_key : "comments_v2"
      # accepted_fields to include in the upload
      # remove a field to filter it out
      accepted_fields:
        - timestamp
        - title
        - attachments.data.external_context.url
        - attachments.media.uri
        - data.comment.timestamp
        - data.comment.comment
        - data.comment.author
        - data.comment.group

    # posts can be split into multiple files
    # that end in `_<number>`.
    your_posts(_(\d)+).json:
      # anonymizers are functions applied on the server
      # that can inspect the content of a potential donation
      # and apply anonymization accordingly.
      # the KEY is the function to apply, the VALUE a string-argument
      anonymizers:
        - fb_redact_posts_usernames_based_on_title : ""
      accepted_fields:
        - timestamp
        - title 
        - attachments.data.external_context.url
        - attachments.data.external_context.name
        - attachments.data.external_context.source
        - attachments.data.for_sale_item.title
        - attachments.data.for_sale_item.price
        - attachments.data.for_sale_item.seller
        - attachments.data.for_sale_item.created_timestamp
        - attachments.data.for_sale_item.updated_timestamp
        - attachments.data.for_sale_item.category
        - attachments.data.for_sale_item.marketplace
        - attachments.data.for_sale_item.location.coordinate.lattitude
        - attachments.data.for_sale_item.location.coordinate.longitude
        - attachments.data.for_sale_item.description
        - attachments.data.media.uri
        - attachments.data.media.creation_timestamp
        - attachments.data.media.media_metadata.upload_ip
        - attachments.data.media.title
        - data.post
        - data.update_timestamp

    # these are the likes & reactions of pages
    pages.json:
      in_key : page_likes
      accepted_fields:
        - name
        - timestamp

    ## alternative filename for likes & reactions of pages
    pages_you've_liked.json:
      in_key : page_likes_v2
      accepted_fields:
        - name
        - timestamp



    # these are the likes & reactions of posts & comments
    posts_and_comments.json:
      in_key: reactions_v2
      accepted_fields:
        - timestamp
        - data.reaction.reaction
        - data.reaction.actor
        - title

    # Advertiser interactions file
    advertisers_you've_interacted_with.json:
      in_key : history_v2
      accepted_fields:
        - title
        - action
        - timestamp

    # Advertisers who uploaded user information
    advertisers_who_uploaded_a_contact_list_with_your_information.json:
      in_key : custom_audiences_v2
      accepted_fields: []